# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
configHash: "1" # configuration change detection
codenow:
  instance: ""
  applicationName: ""
  applicationRuntimeName: ""
  applicationVersion: ""
  componentRuntimeName: "openvpn"
  componentName: "openvpn"
  componentVersion: ${project.version}
  templateId: ""
  domainName: "metrans.codenow.com"
  environmentId: ""

environmentVariables: {}

buildNumber: "${env.BUILD_NUMBER}"

image:
  pullPolicy: Always #IfNotPresent

service:
  type: ClusterIP
  port: 80
  externalEndpointEnabled: true

fluentbit:
  istioProxy:
    enabled: false
    parser: envoy-logging-filter-parser
  parser: oxus-app-component-json

configFiles: {}
environmentVariables: {}

metricsPrometheusEnabled: false
metricsPrometheusStep: PT1M

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}


vpnIp: "" #e.g; "192.168.1.174"
vpnDomain: "" #e.g: "*.private.domain.cz"
openVpnService: "" #e.g. "openvpn.infra.svc.cluster.local"